# SPDX-FileCopyrightText: 2006-2023, Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2023, Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0
name: "CI"

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  NANOBENCH_SUPPRESS_WARNINGS: 1
  TZ: Europe/Berlin

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04,   compiler: spdx_license_lint}
          - {os: ubuntu-22.04,   compiler: gcc-third-latest-cpp20-release}
          - {os: ubuntu-22.04,   compiler: gcc-second-latest-cpp20-release}
          - {os: ubuntu-22.04,   compiler: gcc-latest-cpp20-release}
          - {os: ubuntu-22.04,   compiler: gcc-latest-cpp20-debug-sanitize_address}
          - {os: ubuntu-22.04,   compiler: gcc-latest-cpp20-debug-sanitize_undefined}
          - {os: ubuntu-22.04,   compiler: gcc-latest-cpp20-debug-sanitize_thread}
          - {os: ubuntu-22.04,   compiler: gcc-latest-cpp20-lcov}
          - {os: ubuntu-22.04,   compiler: gcc-latest-cpp23-release}
          - {os: ubuntu-22.04,   compiler: clang-third-latest-cpp20-release}
          - {os: ubuntu-22.04,   compiler: clang-second-latest-cpp20-release}
          - {os: ubuntu-22.04,   compiler: clang-latest-cpp20-release}
          - {os: macos-15-intel, compiler: gcc-latest-cpp20-release}
          - {os: macos-15-intel, compiler: clang-latest-cpp20-release}
          - {os: macos-14,       compiler: gcc-latest-cpp20-release}
          - {os: macos-14,       compiler: clang-latest-cpp20-release}
          - {os: windows-2022,   compiler: msvc-cpp20-release}
          - {os: windows-2022,   compiler: msvc-cpp20-debug}
          - {os: ubuntu-22.04,   compiler: emscripten-cpp20-release}
    steps:
      - name: Standard IV-project testing
        uses: iv-project/IVaction@v11.1
        with:
          compiler: ${{ matrix.compiler }}
          threads: 2
